# Generated by Django 5.1.7 on 2025-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(default='No Description Added'),
            preserve_default=False,
        ),
    ]
